export default {
  ALIGNMENT_ACCURACY: "alignment-accuracy-part",
  ARC_STABILITY: "arc-stability-part",
  ASSEMBLY_LINE: "assembly-line-machine",
  BELT_SPEED: "belt-speed-part",
  CAMERA_CALIBRATION: "camera-calibration-part",
  COLOR_CONSISTENCY: "color-consistency-part",
  COOLING_EFFICIENCY: "cooling-efficiency-part",
  CRITERIA_SETTINGS: "criteria-settings-part",
  ELECTRODE_WEAR: "electrode-wear-part",
  FITTING_TOLERANCE: "fitting-tolerance-part",
  FLOW_RATE: "flow-rate-part",
  LIGHT_INTENSITY: "light-intensity-part",
  LOG_PART_NAV_BUTTON: "log-part-nav-btn",
  MACHINE_STATE_NAV_BUTTON: "machine-state-nav-btn",
  NOZZLE_CONDITION: "nozzle-condition-part",
  PRESSURE: "pressure-part",
  SAVE_PART_BUTTON: "save-part-button",
  SAVED_CONFIRM_MSG: "Saved ✔️",
  SEAM_WIDTH: "seam-width-part",
  SHIELDING_PRESSURE: "shielding-pressure-part",
  SOFTWARE_VERSION: "software-version-part",
  SPEED: "speed-part",
  PAINTING_STATION: "painting-station-machine",
  PART_VALUE_INPUT: "part-value-input",
  QUALITY_CONTROL: "quality-control-machine",
  VIBRATION_LEVEL: "vibration-level-part",
  WELDING_ROBOT: "welding-robot-machine",
  WIRE_FEED_RATE: "wire-feed-rate-part",
};
