export default {
  ALIGNMENT_ACCURACY: "Alignment Accuracy",
  ARC_STABILITY: "Arc Stability",
  ASSEMBLY_LINE: "Assembly Line",
  BELT_SPEED: "Belt Speed",
  CALCULATE_HEALTH_BUTTON: "calculate-health-btn",
  CAMERA_CALIBRATION: "Camera Calibration",
  COLOR_CONSISTENCY: "Color Consistency",
  COOLING_EFFICIENCY: "Cooling Efficiency",
  CRITERIA_SETTINGS: "Criteria Settings",
  ELECTRODE_WEAR: "Electrode Wear",
  FACTORY_HEALTH_SCORE_HEADER: "Factory Health Score",
  FACTORY_HEALTH_SCORE_ABSENT_MSG: "Not yet calculated",
  FITTING_TOLERANCE: "Fitting Tolerance",
  FLOW_RATE: "Flow Rate",
  LIGHT_INTENSITY: "Light Intensity",
  LOG_PART_NAV_BUTTON: "log-part-nav-btn",
  MACHINE_STATE_NAV_BUTTON: "machine-state-nav-btn",
  NOZZLE_CONDITION: "Nozzle Condition",
  PRESSURE: "Pressure",
  RESET_MACHINE_DATA: "reset-data-btn",
  SAVE_PART_BUTTON: "save-part-button",
  SAVED_CONFIRM_MSG: "Saved ✔️",
  SEAM_WIDTH: "Seam Width",
  SHIELDING_PRESSURE: "Shielding Pressure",
  SOFTWARE_VERSION: "Software Version",
  SPEED: "Speed",
  PAINTING_STATION: "Painting Station",
  PART_VALUE_INPUT: "part-value-input",
  QUALITY_CONTROL: "Quality Control Station",
  VIBRATION_LEVEL: "Vibration Level",
  WELDING_ROBOT: "Welding Robot",
  WIRE_FEED_RATE: "Wire Feed Rate",
};
